### ISSUE TITLE
Sifon.csproj OutputPath referring to path outside of solution scope

### ISSUE THREAD

**Issue by binboydotnet** [MartinMiles/Sifon#1]
Sifon.csproj contains:

> <OutputPath>..\..\..\RssbPlatform.Installer\</OutputPath>

 for both Debug and Release. That refers to a folder outside of solution scope what makes it unpredictable and dependant on local folder structure.
**Suggested fix**: do not step out of root solution folder

**Comment by MartinMiles** [comment]
Currently,  the `OutputPath ` parameter indeed points to a folder outside the solution root, which is: `c:\Program Files\Sifon`

That has been done by intense in order to simplify the development, as this folder coincides with a deployment default folder. An installer is being created from that folder on the development machine

**Comment by MartinMiles** [comment]
Closed
